all: addition multiplication

addition: addition.c
	gcc -std=c99 addition.c -o addition

multiplication: multiplication.c
	gcc -std=c99 multiplication.c -o multiplication

clean:
	rm addition multiplication
